{"name": "test_kullanıcı_doğru_bilgiyle_giriş_yaparsa_ana_sayfaya_ulaşır", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Kayıt Listesi' == 'Merhaba, baş...riş yaptınız!'\n  \n  \u001b[0m\u001b[91m- Merhaba, başarılı giriş yaptınız!\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\n  \u001b[92m+ Kayıt Listesi\u001b[39;49;00m\u001b[90m\u001b[39;49;00m", "trace": "fixturefunc = <function see_home at 0x000001590A34E3E0>\nrequest = <FixtureRequest for <Function test_kullanıcı_doğru_bilgiyle_giriş_yaparsa_ana_sayfaya_ulaşır>>\nkwargs = {'page': <Page url='http://127.0.0.1:5000/list'>}\n\n    def call_fixture_func(\n        fixturefunc: _FixtureFunc[FixtureValue], request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if inspect.isgeneratorfunction(fixturefunc):\n            fixturefunc = cast(Callable[..., Generator[FixtureValue]], fixturefunc)\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n                             ^^^^^^^^^^^^^^^^^^^^^\n\nvenv\\Lib\\site-packages\\_pytest\\fixtures.py:929: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npage = <Page url='http://127.0.0.1:5000/list'>\n\n    @then(\"ana sayfa mesajını görürüm\")\n    def see_home(page):\n>       assert page.locator(\"h2\").inner_text() == \"Merhaba, başarılı giriş yaptınız!\"\nE       AssertionError: assert 'Kayıt Listesi' == 'Merhaba, baş...riş yaptınız!'\nE         \nE         \u001b[0m\u001b[91m- Merhaba, başarılı giriş yaptınız!\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\nE         \u001b[92m+ Kayıt Listesi\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\n\ntests\\steps\\test_login_steps.py:23: AssertionError"}, "description": "D:\\Personal\\_Project\\2025\\universal-test-lab\\tests\\features\\login.feature: Kullanıcı doğru bilgiyle giriş yaparsa ana sayfaya ulaşır", "start": 1752506392973, "stop": 1752506393210, "uuid": "803714df-68cd-46ba-b37e-a711afb62578", "historyId": "341eeed72d05c02b47669740bbdf6ff8", "testCaseId": "341eeed72d05c02b47669740bbdf6ff8", "fullName": "tests.steps.test_login_steps#test_kullanıcı_doğru_bilgiyle_giriş_yaparsa_ana_sayfaya_ulaşır", "labels": [{"name": "parentSuite", "value": "tests.steps"}, {"name": "suite", "value": "test_login_steps"}, {"name": "host", "value": "EVT02136NB"}, {"name": "thread", "value": "41888-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.steps.test_login_steps"}]}